### ISSUE TITLE
Counts is not equal to 29 for Overnight mode: UA time - 24 rows, US - 26 rows

### ISSUE THREAD

**Issue by MarynaKulyk2016** [alex-pancho/timedox.com#17]
![image](https://user-images.githubusercontent.com/24566431/37872906-a80ad382-3019-11e8-947a-e73d5f2571e0.png)
![image](https://user-images.githubusercontent.com/24566431/37872917-d32b907e-3019-11e8-8e6b-447dcfa2ff51.png)

**Comment by alex-pancho** [comment]
err in chk list
