### ISSUE TITLE
Открытие файла только в режиме чтения

### ISSUE THREAD

**Issue by nlyashuk** [alex-pancho/timedox.com#2]
Environment: OC Windows 7 Максимальная
                      MS Office Excel 2003

Steps to reproduce:
1. Открыть файл Time_Load_1.0.4.5-ft

Expected results:
1. Файл открывается
2. Появляется меню с 5 кнопками

Actual results:
1. Выполняется преобразование файла
2. Появляется окно-сообщение о открытии файла только для чтения.
3. Появляется сообщение о ожидании завершения операции
![screen_timedox](https://user-images.githubusercontent.com/30635139/28843915-84e3a2d4-770b-11e7-820a-86dffa56ecfc.png)
![screen_timedox_2](https://user-images.githubusercontent.com/30635139/28843914-84dfa04e-770b-11e7-9060-07f881075dac.png)

**Comment by alex-pancho** [comment]
сообщите полную версию Excel
потому что на тестовом у меня запускается
https://i.imgur.com/SNYmpRZ.png

**Comment by nlyashuk** [comment]
Версія така сама
![screen](https://user-images.githubusercontent.com/30635139/28884860-480f6ed6-77bc-11e7-8707-68e7473d357b.png)
я
