### ISSUE TITLE
Ошибка при попытке загрузить Dat-файл 

### ISSUE THREAD

**Issue by nlyashuk** [alex-pancho/timedox.com#3]
Environment: OC Windows 7 Максимальная
                      MS Office Excel 2003
Preconditions:
Открыть файл Time_Load_1.0.4.5-ft

Steps to reproduce:
1. Нажать на первую кнопку Import 
2. Выбрать dat-файл 
3. Указать дату из периода охвата файла

Expected results:
После выбора файла и указания даты данные из файла загружаются

Actual results:
1. После нажатия кнопки Import вызывается окно открытия файла
2. После выбора dat-файла открывается окно выбора месяца и года
3. После указания даты из периода охвата файла появляется сообщение об ошибке
![screen_timedox](https://user-images.githubusercontent.com/30635139/28844827-98be4ae0-770e-11e7-82c2-f3d78074584b.png)

**Comment by alex-pancho** [comment]
имя файла из набора, какую дату выбирали?

**Comment by alex-pancho** [comment]
Исправлено, загрузите файл заново

**Comment by nlyashuk** [comment]
Загрузила файл, но та же ошибка. Открыть dat-файл можно только тогда, когда Time_Load_1.0.4.7-ft  пересохранить.
