### ISSUE TITLE
Нет возможности выбора значения времени в ячейке С5 в Employee mode

### ISSUE THREAD

**Issue by MarynaKulyk2016** [alex-pancho/timedox.com#5]
**Environment:** OC Windows 10 PRO
MS Office Excel 2016

**Фактический результат:** 
В ячейке C5 при нажатии появляется справа выпадающее меню со стрелочкой, где возможно
  выбрать значения 0 или 1 (как для ячеек С3 и С4)

**Ожидаемый результат:**
В ячейке C5 при нажатии появляется справа выпадающее меню со стрелочкой, где возможно
  выбрать значения времени

<img width="1674" alt="1" src="https://user-images.githubusercontent.com/24566431/37257136-9e71bda6-256d-11e8-90ef-0ac63b40cb4d.png">

**Comment by alex-pancho** [comment]
исправить чек лист
