### ISSUE TITLE
В ячейке C9 возможно выбрать числовое значение от 1 до 15 в Employee mode

### ISSUE THREAD

**Issue by MarynaKulyk2016** [alex-pancho/timedox.com#6]
**Фактический результат:**
В ячейке C9 возможно выбрать числовое значение от 1 до 15
**Ожидаемый результат:**
В ячейке C9 при нажатии появляется справа выпадающее меню со стрелочкой, где возможно 
 выбрать числовое значение от 1 до 10

<img width="1671" alt="2" src="https://user-images.githubusercontent.com/24566431/37257264-b83b5a38-256f-11e8-99e3-61cda946b89f.png">

@alex-pancho

**Comment by alex-pancho** [comment]
исправить чек-лист под Фр
