### ISSUE TITLE
Employee mode закрываеться при переключении на другой xlsx-файл, открывается меню с пятью кнопками

### ISSUE THREAD

**Issue by MarynaKulyk2016** [alex-pancho/timedox.com#7]
**Шаги воспроизведения:**
1. В режиме Employee mode открыть любой ексель-файл
2. Переключится на открытый файл
3. Переключиться обратно на вкладку Employees data
4. Обратить внимание, что вкладка Employees data пустая

**Фактический результат:** 
Employee mode закрываеться при переключении на другой xlsx-файл, открывается меню с пятью кнопками

**Ожидаемый результат:**
При переходе от других документов Excel обратно на страницу работы с программой не пропадают названия колонок, не закрывается файл с Employee

<img width="1672" alt="3" src="https://user-images.githubusercontent.com/24566431/37257430-df6cfaba-2571-11e8-8123-33d16dc51ee5.png">
<img width="1679" alt="4" src="https://user-images.githubusercontent.com/24566431/37257431-df8b021c-2571-11e8-842b-5e81c40c16ff.png">

**Comment by alex-pancho** [comment]
это не смертельно
