### ISSUE TITLE
Количество часов в Total Grand не равно 191,30 часов в Report mode

### ISSUE THREAD

**Issue by MarynaKulyk2016** [alex-pancho/timedox.com#8]
**Шаги воспроизведения:**
1. Импортировать файл 01_may_(1-7).dat. (май 2017);
2. Перейти во вкладку Total

**Фактический результат:** 
Количество часов в Total-листе равно 159,67

**Ожидаемый результат:** 
Количество часов в Total-листе равно 191,30

<img width="1679" alt="5" src="https://user-images.githubusercontent.com/24566431/37268352-23be3948-25ce-11e8-83fe-b2cc09f8cbd8.png">

**Comment by alex-pancho** [comment]
chek your setting
