### ISSUE TITLE
There are no Edit and Total sheets after opening the "02_may_(1-14).dat" file in Report mode

### ISSUE THREAD

**Issue by MarynaKulyk2016** [alex-pancho/timedox.com#9]
**Steps to reproduce:**
1. Open the "01_may_(1-7).dat" file
2. Open the "02_may_(1-14).dat" file
3. Pay attention to the absence of Edit and Total sheets (B16, B17, B18 cells also displayed with # symbols)

**Actual result:**
There are no Edit and Total sheets after opening the "02_may_(1-14).dat" file in Report mode

**Expected result:**
There are Edit and Total sheets after opening the "02_may_(1-14).dat" file in Report mode

![2018-03-12 08 58 11](https://user-images.githubusercontent.com/24566431/37269697-63d4ebb6-25d4-11e8-8aac-c6aa4bde327f.jpg)

**Comment by alex-pancho** [comment]
may be you changed time setting before second load?

2018-03-12 9:04 GMT+02:00 MarynaKulyk2016 <notifications@github.com>:

**Comment by alex-pancho** [comment]
In pc setting. First time you have Ukrainian time, but second - us time.
Bt, save all sheet (btn3)  and try to reproduse

**Comment by MarynaKulyk2016** [comment]
Time settings are the same

![image](https://user-images.githubusercontent.com/24566431/37303416-0fbdae60-2637-11e8-93ec-b7af1d0418b5.png)
![image](https://user-images.githubusercontent.com/24566431/37303469-3815fb6a-2637-11e8-836a-a856dd20ee8f.png)

**Comment by alex-pancho** [comment]
thanks

**Comment by alex-pancho** [comment]
fixed in v.1.1.1.9
